### ISSUE TITLE
EPTLSYMPA-1 Less and bootstrap style refactoring for Respondr

### ISSUE THREAD

**Issue by cousquer** [EsupPortail/esup-portlet-sympa#3]
**Styles for uPortal 4.3 and more**
- Styles in RWD
- add Bootstrap markup
- add bootstrap-fontawesone-checkbox (MIT)
- table reflow Mixin on mobile and on multicolumns layout

**Comment by vbonamy** [comment]
Thank you Christian for your PR #4 -> the next TAG will be the version 5.0 :)

**Comment by cousquer** [comment]
@vbonamy 
thanks. wait a little for the NOTICE PR and the response of Olivier, before switching to 5.0
